name: Bug Report
description: Report a bug or unexpected behavior in the TURBO Stack
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug and what you expected
      placeholder: What happened and what did you expect to happen?
    validations:
      required: true
  
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: How to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Build with...
        2. Run...
        3. See error...
    validations:
      required: true
  
  - type: textarea
    id: additional-info
    attributes:
      label: Additional info
      description: Environment, logs, screenshots, or other relevant details
      placeholder: OS, compiler, error logs, etc.
    validations:
      required: false