name: Feature Request
description: Request a new feature or enhancement for the TURBO Stack
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: What feature would you like?
      description: Describe the feature and why it would be valuable
      placeholder: Describe the feature and its benefits...
    validations:
      required: true
  
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: When/how would you use this feature?
      placeholder: Describe the scenario where this feature would help...
    validations:
      required: true
  
  - type: textarea
    id: additional-info
    attributes:
      label: Additional info
      description: Implementation ideas, alternatives, or other relevant details
      placeholder: Any other thoughts, alternatives, or references...
    validations:
      required: false