name: Task
description: Create a task for project management or development work
title: "[Task]: "
labels: ["management"]
body:
  - type: textarea
    id: description
    attributes:
      label: What needs to be done?
      description: Describe the task and its purpose
      placeholder: Describe the task and why it's needed...
    validations:
      required: true
  
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: How do we know it's done?
      description: What are the completion criteria?
      placeholder: |
        - [ ] Specific deliverable 1
        - [ ] Specific deliverable 2
    validations:
      required: true
  
  - type: textarea
    id: additional-info
    attributes:
      label: Additional info
      description: Dependencies, timeline, implementation ideas, or other details
      placeholder: Dependencies, deadlines, approach ideas, etc.
    validations:
      required: false