name: AMReX Mini-App Unit Tests In Turbo-Specific Containers

on:
  workflow_dispatch:
  push:
  #  branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: hctorres/turbo-containers:ubuntu-spack-gcc-environment
    defaults:
      run:
        shell: bash -elo pipefail {0}
    steps:
      - name: Show container and PATH info
        run: |
          echo "OS release:" && cat /etc/os-release || true
          echo "PATH:" && echo $PATH
          echo "Which spack:" && which spack || echo "spack not found"
          echo "Home:" && echo $HOME
          echo "User:" && whoami
          echo "Current directory:" && pwd
          echo "Listing root directory:" && ls -l /
          echo "Listing home directory:" && ls -l $HOME
      - name: Checkout repository
        uses: actions/checkout@v6
        #with:
        #  submodules: 'recursive'
        #  fetch-depth: 0
      - name: Show environment info
        run: |
          gcc --version
          spack --version
          echo "SPACK_ROOT=${SPACK_ROOT}"
      - name: Modify default CI container environment after checkout
        run: |
          # Directory where you pulled the turbo stack repository
          export TURBO_STACK_ROOT="${GITHUB_WORKSPACE}"
          echo "TURBO_STACK_ROOT=${TURBO_STACK_ROOT}" >> $GITHUB_ENV
          if [ ! -d "${TURBO_STACK_ROOT}" ]; then
            echo "Error: TURBO_STACK_ROOT=${TURBO_STACK_ROOT} is not a valid directory."
            exit 1
          fi

          # Path to the turbo mini-app that should be within the turbo stack repository
          export TURBO_MINI_APP_ROOT=${TURBO_STACK_ROOT}/src/amrex_mini_app
          echo "TURBO_MINI_APP_ROOT=${TURBO_MINI_APP_ROOT}" >> $GITHUB_ENV
          if [ ! -d "${TURBO_MINI_APP_ROOT}" ]; then
            echo "Error: TURBO_MINI_APP_ROOT=${TURBO_MINI_APP_ROOT} is not a valid directory."
            exit 1
          fi

          ## To control build and runtime behavior later
          #export DEBUG=1
          #echo "DEBUG=${DEBUG}" >> $GITHUB_ENV
      - name: Build and Run Unit Tests
        run: |
          $TURBO_MINI_APP_ROOT/build_and_run.sh
