name: turbo-stack CI tests

on:
  push:
    branches: ["main", "ci-tests"]
  pull_request:
    branches: ["main", "ci-tests"]
  

jobs:
  build-symmetric:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install ubuntu dependencies
        shell: bash
        run: |
          echo "Installing dependencies..."
          sudo apt-get update
          sudo apt-get install netcdf-bin
          sudo apt-get install libnetcdf-dev
          sudo apt-get install libnetcdff-dev
          sudo apt-get install openmpi-bin
          sudo apt-get install libopenmpi-dev
          sudo apt-get install linux-tools-common
          echo "::endgroup::"

      - name: Build turbo-stack (GNU)
        run: |
          echo "Building turbo-stack..."
          # Add your build commands here, e.g., make or cmake
          ./build.sh --machine ubuntu --compiler gnu
      
      - uses: actions/upload-artifact@v4
        with:
          name: mom6-symmetric-artifact
          path: ./bin/gnu/MOM6
          retention-days: 1

  run-double-gyre:
    needs: build-symmetric
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Download symmetric artifact
        uses: actions/download-artifact@v4
        with:
          name: mom6-symmetric-artifact
          path: ./bin/gnu/MOM6

      - name: Run double gyre test
        run: |
          echo "Running double gyre test..."
          cd ./examples/double_gyre
          ../..//bin/gnu/MOM6/MOM6