name: Clang-Format

on:
  workflow_dispatch:
  branch:
   - mwaxmonsky/clang-format-workflow

jobs:
  format:
    name: Run Clang-Format
    runs-on: ubuntu-latest

    steps:
      - name: Install Clang-Format
        run: sudo apt-get update && sudo apt-get install clang-format && clang-format --version

      - name: Check out code, run clang format, push changes
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Format code
        run: |
          find ./src/ -type f \( -name '*.hpp' -o -name '*.h' -o -name '*.cpp' \) -exec clang-format -i --style=Google --verbose {} +

      - name: Check for changes
        id: check-changes
        run: |
          git diff --exit-code

